apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}-secret
type: Opaque
data:
  JWT_SECRET: {{.Values.secret.JWT_SECRET | b64enc | quote}}
  DB_HOST: {{.Values.secret.DB_HOST | b64enc | quote}}
  DB_PORT: {{.Values.secret.DB_PORT | b64enc | quote}}
  DB_USER: {{.Values.secret.DB_USER | b64enc | quote}}
  DB_PASSWORD: {{.Values.secret.DB_PASSWORD | b64enc | quote}}
  DB_NAME: {{.Values.secret.DB_NAME | b64enc | quote}}
  AWS_ACCESS_KEY_ID: {{.Values.secret.AWS_ACCESS_KEY_ID | b64enc | quote}}
  AWS_SECRET_ACCESS_KEY: {{.Values.secret.AWS_SECRET_ACCESS_KEY | b64enc | quote}}
  AWS_S3_BUCKET_NAME: {{.Values.secret.AWS_S3_BUCKET_NAME | b64enc | quote}}
  AWS_REGION: {{.Values.secret.AWS_REGION | b64enc | quote}}
  AWS_EC2_METADATA_DISABLED: {{.Values.secret.AWS_EC2_METADATA_DISABLED | b64enc | quote}}
