apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}-secret
type: Opaque
data:
  PORT: {{.Values.secret.PORT | toString | b64enc | quote}}
  NODE_ENV: {{.Values.secret.NODE_ENV | b64enc | quote}}
  MONGO_URI: {{.Values.secret.MONGO_URI | b64enc | quote}}
  USER_SERVICE_URL: {{.Values.secret.USER_SERVICE_URL | b64enc | quote}}
  AWS_ACCESS_KEY_ID: {{.Values.secret.AWS_ACCESS_KEY_ID | b64enc | quote}}
  AWS_SECRET_ACCESS_KEY: {{.Values.secret.AWS_SECRET_ACCESS_KEY | b64enc | quote}}
  AWS_S3_BUCKET_NAME: {{.Values.secret.AWS_S3_BUCKET_NAME | b64enc | quote}}
  AWS_REGION: {{.Values.secret.AWS_REGION | b64enc | quote}}
  AWS_EC2_METADATA_DISABLED: {{.Values.secret.AWS_EC2_METADATA_DISABLED | toString | b64enc | quote}}
