apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: default
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      namespace: default
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{.Values.image}}:{{.Values.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Values.containerPort}}
              name: http
              protocol: TCP
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.appName}}-secret
                  key: DB_NAME



