apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}-secret
type: Opaque
data:
  JWT_SECRET: {{.Values.secret.JWT_SECRET | b64enc | quote}}
  DB_HOST: {{.Values.secret.DB_HOST | b64enc | quote}}
  DB_PORT: {{.Values.secret.DB_PORT | b64enc | quote}}
  DB_USER: {{.Values.secret.DB_USER | b64enc | quote}}
  DB_PASSWORD: {{.Values.secret.DB_PASSWORD | b64enc | quote}}
  DB_NAME: {{.Values.secret.DB_NAME | b64enc | quote}}