apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http