apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: default
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      namespace: default
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{.Values.image}}:{{.Values.tag}}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.containerPort}}
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{.Values.appName}}-secret


