apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}-secret
type: Opaque
data:
  MONGO_URI: {{.Values.secret.MONGO_URI | b64enc | quote}}
  DB_NAME: {{.Values.secret.DB_NAME | b64enc | quote}}
  EMAIL_HOST: {{.Values.secret.EMAIL_HOST | b64enc | quote}}
  EMAIL_PORT: {{.Values.secret.EMAIL_PORT | b64enc | quote}}
  EMAIL_USERNAME: {{.Values.secret.EMAIL_USERNAME | b64enc | quote}}
  EMAIL_PASSWORD: {{.Values.secret.EMAIL_PASSWORD | b64enc | quote}}
  CLIENT_URL: {{.Values.secret.CLIENT_URL | b64enc | quote}}
  AWS_ACCESS_KEY_ID: {{.Values.secret.AWS_ACCESS_KEY_ID | b64enc | quote}}
  AWS_SECRET_ACCESS_KEY: {{.Values.secret.AWS_SECRET_ACCESS_KEY | b64enc | quote}}
  AWS_S3_BUCKET_NAME: {{.Values.secret.AWS_S3_BUCKET_NAME | b64enc | quote}}
  AWS_REGION: {{.Values.secret.AWS_REGION | b64enc | quote}}
  AWS_EC2_METADATA_DISABLED: {{.Values.secret.AWS_EC2_METADATA_DISABLED | toString | b64enc | quote}}
  STRIPE_SECRET_KEY: {{.Values.secret.STRIPE_SECRET_KEY | b64enc | quote}}
  STRIPE_WEBHOOK_SECRET: {{.Values.secret.STRIPE_WEBHOOK_SECRET | b64enc | quote}}
  STRIPE_CURRENCY: {{.Values.secret.STRIPE_CURRENCY | b64enc | quote}}
  GHN_TOKEN: {{.Values.secret.GHN_TOKEN | b64enc | quote}}
  GHN_URL: {{.Values.secret.GHN_URL | b64enc | quote}}
  PRODUCT_SERVICE_URL: {{.Values.secret.PRODUCT_SERVICE_URL | b64enc | quote}}
  USER_SERVICE_URL: {{.Values.secret.USER_SERVICE_URL | b64enc | quote}}
  NOTIFICATION_SERVICE_URL: {{.Values.secret.NOTIFICATION_SERVICE_URL | b64enc | quote}}
